version: '3.8'
services:
  movies:
    image: divyam1002/paytmmovie:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: divyam1002/paytmtrain:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  recharge:
    image: divyam1002/paytmdth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  dth:
    image: divyam1002/paytmrecharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
~
~
